package vn.compedia.website.auction.entity;

public enum EScope {
    // Scope Public
    PUBLIC("PUBLIC"),
    // Scope AuthFunctionController
    ABOUT_INFO("ABOUT_INFO"),
    ACCOUNT_USER("ACCOUNT_USER"),
    ACCOUNT_OFFICIALS("ACCOUNT_OFFICIALS"),
    API_PAPER("API_PAPER"),
    API_RELIGION("API_RELIGION"),
    API_NATION("API_NATION"),
    API_EDUCATION("API_EDUCATION"),
    API_REGULAR("API_REGULAR"),
    API_RELATIONSHIP("API_RELATIONSHIP"),
    API_CAREER_GROUP("API_CAREER_GROUP"),
    API_CURRENCY("API_CURRENCY"),
    API_SEX("API_SEX"),
    API_POSITION("API_POSITION"),
    API_MANAGEMENT_LEVEL("API_MANAGEMENT_LEVEL"),
    API_MANAGEMENT_AGENCY("API_MANAGEMENT_AGENCY"),
    API_FOLK("API_FOLK"),
    API_JOB("API_JOB"),
    API_OFFICIALS("API_OFFICIALS"),
    API_BUSINESS("API_BUSINESS"),
    ASSET("ASSET"),
    ASSIGN_AUCTIONEER("ASSIGN_AUCTIONEER"),
    AUCTION_FORMALITY("AUCTION_FORMALITY"),
    AUCTION_MANAGE("AUCTION_MANAGE"),
    AUCTION_METHOD("AUCTION_METHOD"),
    AUCTION_REGISTER("AUCTION_REGISTER"),
    AUCTION_REQ("AUCTION_REQ"),
    BANNER("BANNER"),
    COMMUNE("COMMUNE"),
    CONTACT_INFO("CONTACT_INFO"),
    CONTACT_INFO_LH("CONTACT_INFO_LH"),
    CHECK_DIGITAL_SIGN("CHECK_DIGITAL_SIGN"),
    DECISION("DECISION"),
    DISTRICT("DISTRICT"),
    HISTORY_SYSTEM("HISTORY_SYSTEM"),
    LINK("LINK"),
    NEWS("NEWS"),
    PAYMENT("PAYMENT"),
    PROCEDURE_GUIDE("PROCEDURE_GUIDE"),
    PROVINCE("PROVINCE"),
    RECEIPT_MANAGEMENT("RECEIPT_MANAGEMENT"),
    REGULATION("REGULATION"),
    ROLE("ROLE"),
    STATS_REPORT("STATS_REPORT"),
    SYSTEM_CONFIG("SYSTEM_CONFIG"),
    SYSTEM_MANAGE("SYSTEM_MANAGE"),
    TYPE_ASSET("TYPE_ASSET");

    private String scope;

    EScope(String scope) {
        this.scope = scope;
    }

    public String getScope() {
        return scope;
    }

    public void setScope(String scope) {
        this.scope = scope;
    }
}
